# Generated by Django 5.2.5 on 2025-08-15 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('player', 'Player'), ('captain', 'Captain'), ('admin', 'Administrator'), ('superadmin', 'Super Administrator')], default='player', max_length=10),
        ),
    ]
