# Generated by Django 5.2.5 on 2025-08-16 15:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='esports.game')),
            ],
            options={
                'unique_together': {('admin', 'game')},
            },
        ),
    ]
