# Generated by Django 5.2.5 on 2025-08-21 20:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esports', '0003_admingame'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admingame',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_assignments', to='esports.game'),
        ),
        migrations.AlterField(
            model_name='game',
            name='bases',
            field=models.FileField(upload_to='bases/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='game',
            name='images',
            field=models.ImageField(upload_to='games/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
